<?php

namespace CombBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AsignacionMensualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionMensualRepository extends EntityRepository
{
}
