<?php

namespace CombBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarroRepository extends EntityRepository
{
}
