<?php

namespace CombBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChipRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function filter()
    {
        $firstDay = date('Y') . '-' . date('m') . '-' . '1 00:00:00';
        $lastDay = date('Y') . '-' . date('m') . '-' . date('t') . ' 23:59:59';

        $qb = $this->createQueryBuilder('c');

        $qb->andWhere($qb->expr()->gte('c.fecha', ':firstDay'))
            ->setParameter('firstDay', $firstDay);

        $qb->andWhere($qb->expr()->lte('c.fecha', ':lastDay'))
            ->setParameter('lastDay', $lastDay);

        $qb->orderBy('c.id', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
