<?php

namespace CombBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChipRepository extends EntityRepository
{
}
