<?php

namespace CombBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientUploadedResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientUploadedResourceRepository extends EntityRepository
{
}
