<?php

namespace CombBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DistribucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistribucionRepository extends EntityRepository
{
}
