<?php

namespace CombBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlanAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanAsignacionRepository extends EntityRepository
{
}
