<?php

namespace CombBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TarjetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarjetaRepository extends EntityRepository
{
}
