# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, in_memory]
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user: {password: "$2y$13$mO/BvP3/lkbELN3Bpfr.cetrDQVY9NHErw5Cytajxzcj.vR7KoVgW", roles: ['ROLE_USER'] }
                    admin: { password: "$2y$13$j78ybwNIrRvOh5JX8.YXD.7ZB9N5KN9sQceQd25PIkN2YiWzf53eq", roles: [ 'ROLE_ADMIN' ] }
                    superadmin: { password: "$2y$13$QvWmvERMqYwEebPiaxrns.gH6rlMIFDuwNrmQYQYdiEEYHljju8vC", roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|assets)/
            security: false

        secured_area:
            pattern: ^/
            security: true
            form_login:
                provider: chain_provider
                csrf_token_generator: security.csrf.token_manager
#                success_handler: app.cashier.assign.cashbox
            logout: ~
            anonymous: ~
#            http_basic: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
#        - { path: ^/enterprise/, role: [ROLE_ADMIN] }
#        - { path: ^/client/, role: [ROLE_USER] }
#        - { path: ^/clientsgroup/, role: [ROLE_USER] }
#        - { path: ^/playlist/, role: [ROLE_USER] }
        - { path: ^/, role: ROLE_USER }