# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.twig.constant_extension:
      class: AppBundle\Twig\GetConstantExtension
      tags:
        - { name: twig.extension }

    app.twig.status_label:
      class: AppBundle\Twig\StatusLabelExtension
      tags:
        - { name: twig.extension }